-- Перепись: Большая экспедиция — v14.9
-- ШАГ 1. Выполнить в Supabase Dashboard -> SQL Editor после 00_SUPABASE_PRECHECK.sql.
-- Скрипт рассчитан на повторный запуск (idempotent там, где это возможно).

begin;

-- 1. Общий рейтинг.
-- Если функция использует RLS только неявно, SECURITY DEFINER позволит ей читать общий зачёт.
-- Если внутри определения есть явный auth.uid(), скрипт НЕ изменяет такую функцию и выводит WARNING:
-- её надо переписать по фактической схеме данных, а не обходить вслепую.
do $$
declare r record;
declare def text;
begin
  for r in
    select p.oid, p.oid::regprocedure as signature
    from pg_proc p
    join pg_namespace n on n.oid=p.pronamespace
    where n.nspname='public'
      and p.prokind='f'
      and p.proname in ('census_leaderboard','census_region_leaderboard')
  loop
    def := pg_get_functiondef(r.oid);
    if def ~* 'auth[.]uid\s*\(' then
      raise warning 'Функция % содержит явный auth.uid(); автоматическое изменение пропущено. Скопируйте её определение из PRECHECK для точечного исправления.', r.signature;
    else
      execute format('alter function %s security definer', r.signature);
      execute format('alter function %s set search_path = public, pg_temp', r.signature);
      execute format('revoke all on function %s from public', r.signature);
      execute format('grant execute on function %s to authenticated', r.signature);
      raise notice 'Функция % переведена в SECURITY DEFINER.', r.signature;
    end if;
  end loop;
end $$;

-- 2. Приватная таблица обратной связи.
create table if not exists public.census_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  run_id uuid null,
  tournament text not null default 'colleagues-2026',
  build text null,
  game_version text null,
  nickname text null,
  region integer null check (region between 0 and 5),
  region_name text null,
  mode text null,
  kind text not null default 'bug' check (kind in ('bug','ui','content','idea','other')),
  message text not null default '',
  screenshot_path text null,
  context jsonb not null default '{}'::jsonb,
  status text not null default 'new' check (status in ('new','in_progress','fixed','closed')),
  created_at timestamptz not null default now()
);

alter table public.census_feedback enable row level security;
revoke all on public.census_feedback from anon, authenticated;

create or replace function public.census_submit_feedback(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user uuid := auth.uid();
  v_id bigint;
  v_message text := left(coalesce(p_payload->>'message',''),4000);
  v_path text := nullif(p_payload->>'screenshot_path','');
begin
  if v_user is null then raise exception 'authentication required'; end if;
  if octet_length(coalesce(p_payload::text,'')) > 30000 then raise exception 'feedback payload too large'; end if;
  if length(trim(v_message))=0 and v_path is null then raise exception 'empty feedback'; end if;

  insert into public.census_feedback(
    user_id,run_id,tournament,build,game_version,nickname,
    region,region_name,mode,kind,message,screenshot_path,context
  ) values (
    v_user,
    case when coalesce(p_payload->>'run_id','') ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
      then (p_payload->>'run_id')::uuid else null end,
    left(coalesce(p_payload->>'tournament','colleagues-2026'),120),
    left(coalesce(p_payload->>'build',''),120),
    left(coalesce(p_payload->>'game_version',''),120),
    left(coalesce(p_payload->>'nickname',''),120),
    case when (p_payload->>'region') ~ '^[0-5]$' then (p_payload->>'region')::integer else null end,
    left(coalesce(p_payload->>'region_name',''),160),
    left(coalesce(p_payload->>'mode',''),80),
    case when p_payload->>'kind' in ('bug','ui','content','idea','other') then p_payload->>'kind' else 'other' end,
    v_message,
    v_path,
    coalesce(p_payload->'context','{}'::jsonb)
  ) returning id into v_id;

  return jsonb_build_object('ok',true,'id',v_id);
end $$;

revoke all on function public.census_submit_feedback(jsonb) from public;
grant execute on function public.census_submit_feedback(jsonb) to authenticated;

-- 3. Закрытый Storage bucket для снимков.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values ('census-feedback','census-feedback',false,3145728,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update
set public=false,
    file_size_limit=3145728,
    allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists census_feedback_upload_own on storage.objects;
create policy census_feedback_upload_own
on storage.objects for insert to authenticated
with check (
  bucket_id='census-feedback'
  and (storage.foldername(name))[1] = auth.uid()::text
);

commit;
